apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
---
apiVersion: v1
kind: Service
metadata:
  name: rocketapp-deployment
  namespace: dev
  labels:
    app: rocket-svc
spec:
  type: LoadBalancer
  selector:
    app: rocket-app
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketapp-deployment
  namespace: dev
  labels:
    app: rocketapp-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rocket-app
  template:
    metadata:
      labels:
        app: rocket-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - name: rocket-app
        imagePullPolicy: IfNotPresent
        image: rocketapp
        ports:
          - containerPort: 5005
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 250Mi
            cpu: 400m